### ISSUE TITLE
Document iteration over state.map()

### ISSUE THREAD

**Issue by aspiers** [aergoio/guide#19]
It's not clear from the guide whether it's possible to iterate over a `state.map()`.  Based on my reading of [`contract/state_module.c`](https://github.com/aergoio/aergo/blob/develop/contract/state_module.c), I see that `state_array_iter` is implemented, but there is no corresponding `state_map_iter`.  So it seems that this is not possible.  If I'm right then this limitation should be documented, and it should be made clear that it doesn't behave like a normal table.

I have found a workaround, which is to use a `state.value()` and then set it to a table, but this makes reading/writing quite awkward.

**Comment by graup** [comment]
Maybe @mlogue76 can help?

**Comment by mlogue76** [comment]
It does not support iteration of state.map.
Iterable state.map will be supported in the next hard fork.

**Comment by aspiers** [comment]
OK thanks for confirming!  Very roughly when is the next hard fork expected?  If it's still at least a few months away then maybe it's worth documenting this limitation and the workaround I found.

**Comment by mlogue76** [comment]
The hard fork(SQL in Public) is officially scheduled in Q4.

**Comment by aspiers** [comment]
OK thanks for the info.  Maybe I can find the time to submit a PR to the docs - but probably not for the next few weeks.

**Comment by kroggen** [comment]
AFAIK they keys are hashed and only the hashes are stored, so there is no way to iterate over a `state.map`
